# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:

  # jwt token auth
  # Add somewhere to your secrets yml
  # "config/secrets.yml"
  jwt_secret: '38af0483c50d39ebd0b58ea81a3fc366c1995c4da5bsuperrandomkey'
  jwt_expiration_hours: 18
  
  secret_key_base: d81cb86e041585923155d1dea97bb73f4115efcb62a1f4814233c22da0fcb2ffe764006edc448dc6a9374be3b6b09acbaa4a5a84d54f832492cc2aa07b5bca25

test:
  secret_key_base: fb2c7623cb9f6a05fecd31b6783e571e4cce5b33ef6ee69eaeeee4d77df25599480e1c09554507e04c7830ce1ebcd3914614d2d0676082f5c040416beb9dd4b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:

  # jwt token auth
  # Add somewhere to your secrets yml
  # "config/secrets.yml"
  jwt_secret: '62d2f8f20c9852a2da46b9332c8ec62ba95d82509a7c758evenmoresuperrandomkey'
  jwt_expiration_hours: 18
  
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
